---
- name: Set up multiple authorized keys
  authorized_key:
    user: vagrant
    state: present
    key: '{{ item }}'
  with_file:
    - keyvm4
    
# - name: copiar sshd_config
#   become: yes
#   copy:
#         src: sshd_config
#         dest: /etc/ssh/sshd_config
#         mode: '0644'
#         owner: root
#         group: root

# - name: reiniciar el servicio de sshd
#   become: yes
#   systemd:
#         state: restarted
#         name: sshd
