# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
#### CUANTAS MAQUINAS VIRTUALES QUIERES CREAR?
VM_NUMBER=4
#### CUANTOS DISCOS QUIERES QUE TENGA CADA VM?
DISK_NUMBER=10
  (1..VM_NUMBER).each do |i|
    config.vm.define "vm#{i}" do |node|
        node.vm.box = "centos/7"
        node.vm.hostname = "vm#{i}"
        node.vm.network :private_network, ip: "10.0.0.1#{i}"

        if i==1
          node.vm.network "forwarded_port", guest: 5601, host: 5601
        end
        if i==1
          node.vm.network "forwarded_port", guest: 80, host: "80"
        end
        node.vm.provider "virtualbox" do |vb|
        if i==0
          vb.memory = "128"
        else
          vb.memory = "128"
        end
          vb.cpus = 1
      vb.customize ["storagectl", :id, "--name", "SATA Controller", "--add", "sata", "--controller", "IntelAHCI"]

  ######
        (0..DISK_NUMBER).each do |p|
          d=p
          unless File.exist? ("extra_data_#{i}_#{p}_#{d}.vdi")
            vb.customize ['createhd', '--filename', "extra_data_#{i}_#{p}_#{d}.vdi", '--size', 5 * 1024,'--format', "VDI"]
          end
          # unless File.exist? ("docker_data#{i}_#{p}_#{d}.vdi")
          #   vb.customize ['createhd', '--filename', "docker_data_#{i}_#{p}_#{d}.vdi", '--size', 6 * 1024]
          # end
              vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', "#{p}", '--device', 0, '--type',  'hdd', '--medium', "extra_data_#{i}_#{p}_#{d}.vdi"]
             # vb.customize ['storageattach', :id, '--storagectl', 'IDE', '--port', "#{p}", '--device', 0, '--type',  'hdd', '--medium', "docker_data_#{i}_#{p}_#{d}.vdi"]
        end
    end
  end
end
end
